#!/usr/bin/env python3
"""Decode default@2x.png (64x64 GA8), box-downscale to 32x32 ARGB8888, emit C include."""
from __future__ import annotations

import struct
import sys
import zlib
from pathlib import Path


def read_png_ga_rgba(path: Path) -> tuple[int, int, list[tuple[int, int, int, int]]]:
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise SystemExit("not a PNG")
    pos = 8
    w = h = 0
    idat = bytearray()
    while pos < len(data):
        ln = struct.unpack(">I", data[pos : pos + 4])[0]
        pos += 4
        typ = data[pos : pos + 4]
        pos += 4
        chunk = data[pos : pos + ln]
        pos += ln
        pos += 4  # crc
        if typ == b"IHDR":
            w, h, bd, ct, comp, filt, inter = struct.unpack(">IIBBBBB", chunk)
            if bd != 8 or ct != 4 or inter != 0:
                raise SystemExit(f"expected 8-bit grayscale+alpha, got bd={bd} ct={ct} inter={inter}")
        elif typ == b"IDAT":
            idat.extend(chunk)
        elif typ == b"IEND":
            break
    raw = zlib.decompress(bytes(idat))
    stride = w * 2 + 1
    out = [[0, 0, 0, 0] for _ in range(w * h)]
    prev = bytearray(stride)
    i = 0
    for y in range(h):
        f = raw[i]
        i += 1
        row = bytearray(raw[i : i + w * 2])
        i += w * 2
        if f == 1:  # Sub
            for x in range(0, len(row), 2):
                if x >= 2:
                    row[x] = (row[x] + row[x - 2]) & 255
                    row[x + 1] = (row[x + 1] + row[x - 1]) & 255
        elif f == 2:  # Up
            for x in range(len(row)):
                row[x] = (row[x] + prev[x + 1]) & 255
        elif f == 3:  # Average
            for x in range(0, len(row), 2):
                left_g = row[x - 2] if x >= 2 else 0
                left_a = row[x - 1] if x >= 2 else 0
                up_g = prev[x + 1]
                up_a = prev[x + 2]
                row[x] = (row[x] + ((left_g + up_g) // 2)) & 255
                row[x + 1] = (row[x + 1] + ((left_a + up_a) // 2)) & 255
        elif f == 4:  # Paeth
            def paeth(a, b, c):
                p = a + b - c
                pa = abs(p - a)
                pb = abs(p - b)
                pc = abs(p - c)
                if pa <= pb and pa <= pc:
                    return a
                if pb <= pc:
                    return b
                return c

            for x in range(0, len(row), 2):
                a_g = row[x - 2] if x >= 2 else 0
                a_a = row[x - 1] if x >= 2 else 0
                b_g = prev[x + 1]
                b_a = prev[x + 2]
                c_g = prev[x - 1] if x >= 2 else 0
                c_a = prev[x] if x >= 2 else 0
                row[x] = (row[x] + paeth(a_g, b_g, c_g)) & 255
                row[x + 1] = (row[x + 1] + paeth(a_a, b_a, c_a)) & 255
        prev[:] = b"\0" + row
        for x in range(w):
            g, a = row[x * 2], row[x * 2 + 1]
            out[y * w + x] = [g, g, g, a]
    return w, h, out


def downscale_half(w: int, h: int, px: list) -> list[int]:
    if w % 2 or h % 2:
        raise SystemExit("need even dimensions")
    nw, nh = w // 2, h // 2
    out = []
    for y in range(nh):
        for x in range(nw):
            acc_g = acc_a = 0
            for dy in (0, 1):
                for dx in (0, 1):
                    r, g, b, a = px[(y * 2 + dy) * w + (x * 2 + dx)]
                    acc_g += r
                    acc_a += a
            g4 = (acc_g + 2) // 4
            a4 = (acc_a + 2) // 4
            out.append((a4 << 24) | (g4 << 16) | (g4 << 8) | g4)
    return out


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    png = root / "default@2x.png"
    if len(sys.argv) > 1:
        png = Path(sys.argv[1])
    if not png.is_file():
        raise SystemExit(f"missing {png}")
    w, h, px = read_png_ga_rgba(png)
    if (w, h) != (64, 64):
        print(f"warning: expected 64x64, got {w}x{h}", file=sys.stderr)
    argb = downscale_half(w, h, px)
    # Match default.svg viewBox + translate(10,7) — logical hotspot for 32px asset.
    hot_x, hot_y = 10, 7
    out_path = root / "kernel" / "src" / "assets" / "cursor_default.inc"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Generated by scripts/gen_cursor_rgba.py from default@2x.png — do not edit. */",
        "#define CURSOR_DEFAULT_W 32u",
        "#define CURSOR_DEFAULT_H 32u",
        f"#define CURSOR_DEFAULT_HOT_X {hot_x}",
        f"#define CURSOR_DEFAULT_HOT_Y {hot_y}",
        "static const uint32_t cursor_default_rgba[32 * 32] = {",
    ]
    for i in range(0, len(argb), 8):
        chunk = ", ".join(f"0x{v:08x}u" for v in argb[i : i + 8])
        lines.append("    " + chunk + ",")
    lines[-1] = lines[-1].rstrip(",")  # last line comma
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(argb)} pixels)")


if __name__ == "__main__":
    main()
